# Название этого workflow (процесса). Можете назвать его как угодно, для понимания.
name: Add codesandbox link

# Секция, определяющая КОГДА этот workflow будет запускаться.
on:
  # 1-й триггер: на событие Pull Request (запрос на слияние)
  pull_request:
    # Но не на любое событие PR, а только когда он ОТКРЫТ (created).
    types: [opened]
  # 2-й триггер: альтернативное событие для безопасности.
  # Используется из-за особенностей безопасности GitHub Actions.
  # Нужно, чтобы workflow из форка репозитория мог оставить комментарий в PR основного репозитория.
  pull_request_target:
    # Также только при открытии.
    types: [opened]

# Секция, определяющая ЧТО делать. Может быть несколько jobs.
jobs:
  # Название одной job (задачи). Внутри нее описываются конкретные шаги.
  codesandbox-comment:
    # Более понятное имя, которое будет отображаться в интерфейсе GitHub.
    name: Add codesandbox link comment
    # Указываем, на какой операционной системе запускать эту job (в данном случае последний Ubuntu).
    runs-on: ubuntu-latest
    # Секция прав доступа. Нужно явно указать, какие разрешения нужны job.
    permissions:
      contents: write  # Запись в репозиторий (на всякий случай, здесь может не требоваться).
      pull-requests: write  # Ключевое право: запись в Pull Request, то есть возможность оставить комментарий.
      repository-projects: write # Запись в проекты репозитория (здесь тоже, вероятно, не используется).

    # Последовательность шагов, которые выполнит job.
    steps:
      # Шаг 1: Используем готовое действие из Marketplace (https://github.com/marketplace/actions/add-pr-comment).
      # Это действие умеет добавлять комментарии в PR.
      - uses: mshick/add-pr-comment@v2
        # Переменные окружения для этого шага.
        env:
          # Передаем специальный токен для аутентификации. GitHub автоматически его создает для каждого запуска.
          # Он нужен действию `add-pr-comment`, чтобы оно имело права оставить комментарий от вашего имени.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Параметры, которые мы передаем в действие `add-pr-comment`.
        with:
          # Сам текст сообщения, которое будет добавлено в комментарий.
          message: |
            You can check this code at CodeSandbox with the link
            # Формируем динамическую ссылку.
            # `github.repository` — это имя вашего репозитория (например, "username/project-name").
            # `github.head_ref` — это название ветки, из которой был создан PR.
            # В итоге ссылка будет выглядеть так: https://githubbox.com/username/project-name/tree/feature-branch
            https://githubbox.com/${{ github.repository }}/tree/${{ github.head_ref }}
